# Generated by Django 4.0 on 2021-12-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_position', models.IntegerField(blank=True, null=True)),
                ('album_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_label', models.CharField(blank=True, max_length=255, null=True)),
                ('album_year', models.CharField(blank=True, max_length=255, null=True)),
                ('album_critic', models.TextField(blank=True, null=True)),
                ('album_genre', models.CharField(blank=True, max_length=255, null=True)),
                ('album_subgenre', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumUserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_order', models.IntegerField(blank=True, default=0, null=True)),
                ('user_ranked_order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_generated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_by_user', to='generator.album')),
                ('user_generated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_album', to='auth.user')),
            ],
        ),
    ]
